spring:
  profiles:
    default:
      - termicron
      #- bundlebuilder
  main:
    banner-mode: off
logging:
  level:
    org: info

bundlebuilder:
  defaults:
    default-servers:
      - https://ontoserver.imi.uni-luebeck.de/fhir
      - https://ontoserver.imi.uni-luebeck.de/koeln/fhir


---
spring:
  config:
    activate:
      on-profile: altport
server:
  port: 8000